name: build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: reviewdog/action-setup@e04ffabe3898a0af8d0fb1af00c188831c4b5893 # v1.3.2
        with:
          reviewdog_version: latest
